### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [skgtech/skgtech.io-docker#1]
- [x] Add https://imagelayers.io/ badge
- [x] Add how to use details to the main repo (https://github.com/skgtech/skgtech.io)
- [x] Add a link to builds list ([hub.docker.com/r/skgtech/website/builds/](https://hub.docker.com/r/skgtech/website/builds/))
- [x] Edit README.md to get the correct links and info.
